// <auto-generated />
using CarPool.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarPool.Services.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220429165944_Create_Initial")]
    partial class Create_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("CarPool.Models.User", b =>
                {
                    b.Property<string>("emailId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("emailId");

                    b.ToTable("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
